### ISSUE TITLE
UX: Change 'qubes-url-redirector' to 'Open in Qube' or similar

### ISSUE THREAD

**Issue by anoadragon453** [raffaeleflorio/qubes-url-redirector#1]
The end goal is to have normal users use this to redirect links. They don't need to know that it's called qubes-url-redirector. Instead, have something more user-friendly like 'Open in Qube' or perhaps 'Send to Qube'.

Thanks for your work!

**Comment by raffaeleflorio** [comment]
Yeah, I agree. I think that 'Open in Qube' is good..

It's a pleasure!
