### ISSUE TITLE
Firefox release and signing

### ISSUE THREAD

**Issue by x4lldux** [raffaeleflorio/qubes-url-redirector#11]
Do consider signing and releasing this extension in it's current state. 
Project was in status quo for the last 2 months without complaints, which means no urgent work was needed. The only currently known bug (#3) has a very limited scope in Qubes environment because Whonix DVM's provide much bigger privacy guarantees than Private Mode in a regular Firefox. 

Also, currently available options of installation suck. One needs either: 

 - to globally disable sign verification - not secure
 - to install it by hand on each launch of FF - not practical

And this addon is already extremely useful in it's current state. So please sign current version 2.1.

**Comment by raffaeleflorio** [comment]
Yeah, you're right. I've just submitted! As soon as I get the signed package, I'll upload it! :smile:

**Comment by x4lldux** [comment]
Wow, super fast 😄 !

**Comment by raffaeleflorio** [comment]
I got it! I've have to change the readme and I'll upload it.

**Comment by raffaeleflorio** [comment]
Done! Installation for Firefox is: `make firefox`. :)
I've also simplified the chrome installation method. :smile:
