### ISSUE TITLE
chrome installation error + enhancement (add keyboard sohrtcut + click )

### ISSUE THREAD

**Issue by idrissaabadi** [raffaeleflorio/qubes-url-redirector#18]
Hello ! i followed the instrcutions to install on chrome and i have these errors : 

Failed to load extension from: ~/Downloads/qubes-url-redirector-master/chrome
Could not load background script 'webextension-browser-proxy/polyfill.js'.

And can you add a keyboard shortcut + click to open in disposavle vm ?
Thank you so much for this exstension !

**Comment by idrissaabadi** [comment]
the webextension-browser-proxy folder is empty i download it separatly than it worked

**Comment by raffaeleflorio** [comment]
You could clone with `git clone --recursive https://github.com/raffaeleflorio/qubes-url-redirector.git`and you'll get every dependencies cloned. No need to download manually and paste. In addition you can also check signatures made to commits.

**Comment by raffaeleflorio** [comment]
> And can you add a keyboard shortcut + click to open in disposavle vm ?

Good idea! :+1:
It could be useful to customize the shortcuts. For example one for dispVM, one for open-here, one for someVM and so on.

> Thank you so much for this exstension !

It's a pleasure! :smile:
