### ISSUE TITLE
Can't open new tab when the exstension is enabled

### ISSUE THREAD

**Issue by idrissaabadi** [raffaeleflorio/qubes-url-redirector#19]
I can't open a new tab in google chrome when the exstension is enabled , but when i disable it i can open a new tab + when i right click open in dispvm nothing happens

**Comment by raffaeleflorio** [comment]
> I can't open a new tab in google chrome when the exstension is enabled 

Hi, in Chrome the new tab is actually a remote HTML page. So the browser **makes** an HTTP(S) request. Currently the URL is: `https://google.com/_/chrome/newtab?ie=UTF-8` (it redirects to the Google Search homepage). For this reason you need to whitelist either the URL or change the behavior of the new tab. I think that the easiest way is with some extensions, however I didn't try. I don't like Google's browser.

I'll add details about this behavior in the README.
**UPDATE:**
I've just added.

>  but when i disable it i can open a new tab + when i right click open in dispvm nothing happens

Did you follow the installation instruction?
The third point of [Chrome instruction](https://github.com/raffaeleflorio/qubes-url-redirector/blob/master/README.md#chromechromium) is responsible to permits the redirect.
If you did everything correctly check the contents of `/.config/google-chrome/NativeMessagingHosts/qvm_open_in_vm.json`  and check the existence (and the exec bit) of `/usr/local/bin/qvm-open-in-vm-we.py`

**Comment by idrissaabadi** [comment]
My bad , i recplaced the exstension id in the downloaded file not in /.config..... Thank you so much !!

**Comment by raffaeleflorio** [comment]
No problem! :)
However I wrote `/.config` where I meant `~/.config`. Now works? If it's ok I close the issue.
