### ISSUE TITLE
Chrome/Chromium new tab behavior

### ISSUE THREAD

**Issue by rugk** [raffaeleflorio/qubes-url-redirector#30]
Is the behaviour you describe under "Chrome/Chromium new tab behavior" really true?

Because I don't see any such URL contacted in the network console in Chrome/ium:
![grafik](https://user-images.githubusercontent.com/11966684/43100369-6c569064-8ec5-11e8-9b63-724da66e8dfc.png)

**Comment by raffaeleflorio** [comment]
@rugk As you can see it's the first row in your screenshot.

**Comment by rugk** [comment]
Wait, where?

As a a size it states something with "[from Service…" there, so I assume this is locally saved. Also, if I select "offline" to not make network requests the new tab page loads just fine.

**Comment by raffaeleflorio** [comment]
I've just tried with the extension and Chromium. It intercepts a request to: https://google.com/_/chrome/newtab?ie=UTF-8. Maybe it's a fake request, however from the extension point of view it's a normal http request.

**Comment by rugk** [comment]
Can you see whether it transmits any POST data or so?

Looking for the URl I can find these:
* https://bugs.chromium.org/p/chromium/issues/detail?id=456420
* https://lh3.googleusercontent.com/-SmwzQ83fqaA/WX9RDIL8TPI/AAAAAAAACu8/x0J5h388FUIvHF9pA7DzMwH-3691jS5CACLcBGAs/s1600/chrome.jpg

So this really seems to be the new tab page of Chrome, so...

So maybe adjust the Readme to mention, it is a "hidden" request, not visible in the network console. (Maybe link to this issue...)

**Comment by raffaeleflorio** [comment]
> Can you see whether it transmits any POST data or so?

If I remember correctly it's a GET request.

> So maybe adjust the Readme to mention, it is a "hidden" request, not visible in the network console. (Maybe link to this issue...)

Yeah, the readme doesn't make this point clear..
