### ISSUE TITLE
`[Dom0] Operation execution` dialog opens when url is supposed to open in another VM

### ISSUE THREAD

**Issue by ghost** [raffaeleflorio/qubes-url-redirector#37]
Hi. I've set `Default Action` in `qubes-url-redirector` to be `Open in the default qube` and `Default qube:` to `untrusted-fdr28`, however when I try to open an url, which should open in the default qube, I am being asked by Qubes (or by `qvm-open-in-vm`) to type the target VM in a dialog, as if it doesn't already know that its name is supposed to be `untrusted-fdr28`.
![askedscreenshot_2018-09-15_03-12-10](https://user-images.githubusercontent.com/40925413/45580766-3c883f00-b895-11e8-8920-5d68439dae99.png)

Is there some policy setting in Qubes that makes this dialog pop-up ? 
I've looked with `grep` in `/etc/qubes-rpc/policy/` but couldn't find anything at first glance.

I've encountered this before in https://github.com/QubesOS/qubes-issues/issues/4207
I'm on Qubes OS 4.0

**Comment by ghost** [comment]
[This](https://github.com/QubesOS/qubes-issues/issues/3251#issuecomment-421551445) helped.

So the policy (file) that I was looking for is: `/etc/qubes-rpc/policy/qubes.OpenURL`

**Comment by raffaeleflorio** [comment]
> [This](https://github.com/QubesOS/qubes-issues/issues/3251#issuecomment-421551445) helped.
> 
> So the policy (file) that I was looking for is: `/etc/qubes-rpc/policy/qubes.OpenURL`

Yeah, it's the R4.0 way. To hide completely the prompt you need to add to `qubes.OpenURL` a `default_target` with the `allow` policy.
So:
```
gmail-basedon-w-s-f-fdr28 your_default_qube allow,default_target=your_default_qube
```

However after this you need to sync the default_target qube in the policy with the "Open in Qube" one.
With the ask policy you get the prompt with the target already entered, but you need to press 'OK'.
