### ISSUE TITLE
Make an icon in "Qubes style"

### ISSUE THREAD

**Issue by raffaeleflorio** [raffaeleflorio/qubes-url-redirector#4]
Currently Qubes icon is used. An icon to represent/identify better the extension is needed. Furthermore the icon will be used to represent different status of the extension. (e.g. red for disabled).

- [x] Enabled icon
- [x]  Disabled icon

**Comment by rugk** [comment]
For some reason this issue haas not been closed by your commit…

**Comment by raffaeleflorio** [comment]
@rugk Commits made to branches other than master doesn't close issues. That commit was made in the [v2.1.1 branch](https://github.com/raffaeleflorio/qubes-url-redirector/tree/v2.1.1).
