### ISSUE TITLE
Doesn't work anymore with Firefox 71.0

### ISSUE THREAD

**Issue by SvenSemmler** [raffaeleflorio/qubes-url-redirector#42]
Since the update to FF 71.0 the Q is red and the plugin doesn't work anymore.

**Comment by raffaeleflorio** [comment]
Hi @SvenSemmler,
sorry for the late reply.. Currently, because work, I'm not using Qubes OS. Sincerely I hope that I can work again on this extension as soon as possibile.
Nonetheless can you send me more info? Like the extension log?
Thanks.

**Comment by SvenSemmler** [comment]
@raffaeleflorio it appears to have been an issue with the Fedora FF 71 binary: https://bugzilla.redhat.com/show_bug.cgi?id=1779570
As of 71.0.1 everything works again.

**Comment by raffaeleflorio** [comment]
Perfect! Thanks for the update!
